[package]
name = "oe-schema-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.117"
winnow = { version = "0.6.9" }
